apiVersion: v1
kind: Service
metadata:
  name: gestionestudiantes-nodeport-service
spec:
  type: NodePort
  selector:
    app: gestionestudiantesservice
  ports:
    - name: gestionestudiantesservice
      protocol: TCP
      port: 8080
      targetPort: 8080