apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: pepe.com
      http:
        paths:
          - path: /api/estudiante
            pathType: Prefix
            backend:
              service:
                name: gestion-estudiantes-clusterip-service
                port:
                  number: 8080
          - path: /api/campus/estudiante
            pathType: Prefix
            backend:
              service:
                name: campus-clusterip-service
                port:
                  number: 8080
