version: '3.9'
services:
  webapp:
    image: pepe/miimagensuprema:1.1
    build: .
    ports:
      - 8090:8080
      - 8091:8081
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/